// <auto-generated />
using System;
using APIVinotrip.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIVinotrip.Migrations
{
    [DbContext(typeof(DBVinotripContext))]
    partial class DBVinotripContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Activite", b =>
                {
                    b.Property<int>("IdActivite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idActivite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActivite"));

                    b.Property<string>("LibelleActivite")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("libelleActivite");

                    b.Property<decimal?>("PrixActivite")
                        .HasColumnType("NUMERIC(8,2)")
                        .HasColumnName("prixActivite");

                    b.HasKey("IdActivite")
                        .HasName("pk_activite");

                    b.ToTable("ACTIVITE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("IdAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idAdresse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdresse"));

                    b.Property<string>("CpAdresse")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cpAdresse");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("idClient");

                    b.Property<int?>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<string>("NAdresse")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nAdresse");

                    b.Property<string>("NomAdresse")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nomAdresse");

                    b.Property<string>("NomAdresseDestinataire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomAdresseDestinataire");

                    b.Property<string>("NomAdresseDestinationFacture")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomAdresseDestinationFacture");

                    b.Property<string>("PaysAdresse")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paysAdresse")
                        .HasDefaultValueSql("'France'::character varying");

                    b.Property<string>("RueAdresse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rueAdresse");

                    b.Property<string>("VilleAdresse")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("villeAdresse");

                    b.HasKey("IdAdresse")
                        .HasName("pk_adresse");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdPartenaire");

                    b.ToTable("ADRESSE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.AutreSociete", b =>
                {
                    b.Property<int>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<string>("MailPartenaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mailPartenaire");

                    b.Property<string>("NomPartenaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomPartenaire");

                    b.Property<string>("Telpartenaire")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telpartenaire")
                        .IsFixedLength();

                    b.HasKey("IdPartenaire")
                        .HasName("pk_autresociete");

                    b.ToTable("AUTRESOCIETE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Avis", b =>
                {
                    b.Property<int>("IdAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idAvis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAvis"));

                    b.Property<DateTime?>("DateAvis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateAvis");

                    b.Property<string>("DescriptionAvis")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("descriptionAvis");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("idClient");

                    b.Property<int?>("IdSejour")
                        .HasColumnType("integer")
                        .HasColumnName("idSejour");

                    b.Property<int?>("NoteAvis")
                        .HasColumnType("integer")
                        .HasColumnName("noteAvis");

                    b.Property<string>("PhotoAvis")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoAvis");

                    b.Property<string>("TitreAvis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titreAvis");

                    b.HasKey("IdAvis")
                        .HasName("pk_avis");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdSejour");

                    b.ToTable("AVIS");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.Property<int>("IdCB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCB");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCB"));

                    b.Property<bool?>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<DateTime?>("DateExpirationCreditCard")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateExpirationCreditCard")
                        .IsFixedLength();

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("idClient");

                    b.Property<string>("NumeroCB")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .HasColumnName("numeroCB")
                        .IsFixedLength();

                    b.Property<string>("NumeroCVCCarte")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("numeroCVCCarte");

                    b.HasKey("IdCB")
                        .HasName("pk_carte_bancaire");

                    b.HasIndex("IdClient");

                    b.ToTable("CARTE_BANCAIRE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CategorieParticipant", b =>
                {
                    b.Property<int>("IdCategorieParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCategorieParticipant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategorieParticipant"));

                    b.Property<string>("LibelleCategorieParticipant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleCategorieParticipant");

                    b.HasKey("IdCategorieParticipant")
                        .HasName("pk_categorieparticipant");

                    b.ToTable("CATEGORIEEPARTICIPANT");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CategorieSejour", b =>
                {
                    b.Property<int>("IdCategorieSejour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCategorieSejour");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategorieSejour"));

                    b.Property<string>("LibelleCategoriesSejour")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleCategoriesSejour");

                    b.HasKey("IdCategorieSejour")
                        .HasName("pk_categoriesejour");

                    b.ToTable("CATEGORIESEJOUR");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CategorieVignoble", b =>
                {
                    b.Property<int>("IdCategorieVignoble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCategorieVignoble");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategorieVignoble"));

                    b.Property<string>("LibelleCategorieVignoble")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleCategorieVignoble");

                    b.HasKey("IdCategorieVignoble")
                        .HasName("pk_categorievignoble");

                    b.ToTable("CATEGORIEVIGNOBLE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Cave", b =>
                {
                    b.Property<int>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<int?>("IdTypeDegustation")
                        .HasColumnType("integer")
                        .HasColumnName("idTypeDegustation");

                    b.Property<string>("MailPartenaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mailPartenaire");

                    b.Property<string>("NomPartenaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomPartenaire");

                    b.Property<string>("TelPartenaire")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telPartenaire")
                        .IsFixedLength();

                    b.HasKey("IdPartenaire")
                        .HasName("pk_cave");

                    b.HasIndex("IdTypeDegustation");

                    b.ToTable("CAVE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idClient");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClient"));

                    b.Property<bool>("A2f")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("a2f");

                    b.Property<bool?>("BloquingClient")
                        .HasColumnType("boolean")
                        .HasColumnName("bloquingClient");

                    b.Property<DateTime?>("DateCreationCompteClient")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateCreationCompteClient");

                    b.Property<DateTime?>("DateCreationToken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateCreationToken");

                    b.Property<DateTime?>("DateDerniereActiviteClient")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateDerniereActiviteClient");

                    b.Property<DateTime?>("DateNaissanceClient")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateNaissanceClient");

                    b.Property<string>("EmailClient")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emailClient");

                    b.Property<int?>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("idRole");

                    b.Property<string>("MdpClient")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mdpClient");

                    b.Property<string>("NomClient")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomClient");

                    b.Property<string>("PrenomClient")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenomClient");

                    b.Property<string>("TelClient")
                        .HasMaxLength(12)
                        .HasColumnType("character(12)")
                        .HasColumnName("telClient")
                        .IsFixedLength();

                    b.Property<string>("TokenResetMDP")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .HasColumnName("tokenResetMDP")
                        .HasDefaultValueSql("NULL::bpchar")
                        .IsFixedLength();

                    b.HasKey("IdClient")
                        .HasName("pk_client");

                    b.HasIndex("IdRole");

                    b.ToTable("CLIENT");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CodePromo", b =>
                {
                    b.Property<int>("IdCodePromo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCodePromo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCodePromo"));

                    b.Property<string>("LibelleCodePromo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("libelleCodePromo");

                    b.Property<int?>("Reduction")
                        .HasColumnType("integer")
                        .HasColumnName("reduction");

                    b.HasKey("IdCodePromo")
                        .HasName("pk_codepromo");

                    b.ToTable("CODEPROMO");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCommande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommande"));

                    b.Property<string>("CodeReduction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codeReduction");

                    b.Property<DateTime?>("DateCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateCommande")
                        .HasDefaultValueSql("'2025-01-01'::date");

                    b.Property<string>("EtatCommande")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("etatCommande")
                        .HasDefaultValueSql("'En attente de validation'::character varying");

                    b.Property<int?>("IdAdresseFacturation")
                        .HasColumnType("integer")
                        .HasColumnName("idAdresseFacturation");

                    b.Property<int?>("IdAdresseLivraison")
                        .HasColumnType("integer")
                        .HasColumnName("idAdresseLivraison");

                    b.Property<int?>("IdCB")
                        .HasColumnType("integer")
                        .HasColumnName("idCB");

                    b.Property<int?>("IdClientAcheteur")
                        .HasColumnType("integer")
                        .HasColumnName("idClientAcheteur");

                    b.Property<int?>("IdClientBeneficiaire")
                        .HasColumnType("integer")
                        .HasColumnName("idClientBeneficiaire");

                    b.Property<int>("IdCodePromo")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("idCodePromo");

                    b.Property<int?>("IdPanier")
                        .HasColumnType("integer")
                        .HasColumnName("idPanier");

                    b.Property<string>("TypePayementCommande")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("typePayementCommande");

                    b.Property<bool>("ValidationClient")
                        .HasColumnType("boolean")
                        .HasColumnName("validationClient");

                    b.HasKey("IdCommande")
                        .HasName("pk_commande");

                    b.HasIndex("IdAdresseFacturation");

                    b.HasIndex("IdAdresseLivraison");

                    b.HasIndex("IdCB");

                    b.HasIndex("IdClientAcheteur");

                    b.HasIndex("IdClientBeneficiaire");

                    b.HasIndex("IdCodePromo");

                    b.HasIndex("IdPanier");

                    b.ToTable("COMMANDE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.DescriptionCommande", b =>
                {
                    b.Property<int>("IdDescriptionCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idDescriptionCommande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescriptionCommande"));

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateFin");

                    b.Property<bool?>("EncaissementMangement")
                        .HasColumnType("boolean")
                        .HasColumnName("encaissementMangement");

                    b.Property<int?>("IdCB")
                        .HasColumnType("integer")
                        .HasColumnName("idCB");

                    b.Property<int?>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("idCommande");

                    b.Property<int?>("IdHebergement")
                        .HasColumnType("integer")
                        .HasColumnName("idHebergement");

                    b.Property<int?>("IdPassegeiment")
                        .HasColumnType("integer")
                        .HasColumnName("idPassegeiment");

                    b.Property<int?>("IdSejour")
                        .HasColumnType("integer")
                        .HasColumnName("idSejour");

                    b.Property<bool?>("IsPDej")
                        .HasColumnType("boolean")
                        .HasColumnName("isPDej");

                    b.Property<int?>("NbAdultes")
                        .HasColumnType("integer")
                        .HasColumnName("nbAdultes");

                    b.Property<int?>("NbChambresDouble")
                        .HasColumnType("integer")
                        .HasColumnName("nbChambresDouble");

                    b.Property<int?>("NbChambresSimple")
                        .HasColumnType("integer")
                        .HasColumnName("nbChambresSimple");

                    b.Property<int?>("NbChambresTriple")
                        .HasColumnType("integer")
                        .HasColumnName("nbChambresTriple");

                    b.Property<int?>("NbEnfants")
                        .HasColumnType("integer")
                        .HasColumnName("nbEnfants");

                    b.Property<bool?>("PDej")
                        .HasColumnType("boolean")
                        .HasColumnName("pDej");

                    b.Property<int?>("PrixOeuf")
                        .HasColumnType("integer")
                        .HasColumnName("prixOeuf");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.Property<bool?>("ValidationClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("validationClient");

                    b.HasKey("IdDescriptionCommande")
                        .HasName("pk_descriptioncommande");

                    b.HasIndex("IdCB");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdHebergement");

                    b.HasIndex("IdSejour");

                    b.ToTable("DESCRIPTIONCOMMANDE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.DescriptionPanier", b =>
                {
                    b.Property<int>("IdDescriptionPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idDescriptionPanier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescriptionPanier"));

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateDebut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateFin");

                    b.Property<bool?>("DisponibiliteHebergement")
                        .HasColumnType("boolean")
                        .HasColumnName("disponibiliteHebergement");

                    b.Property<bool?>("ECoffret")
                        .HasColumnType("boolean")
                        .HasColumnName("eCoffret");

                    b.Property<int?>("IdHebergement")
                        .HasColumnType("integer")
                        .HasColumnName("idHebergement");

                    b.Property<int?>("IdPanier")
                        .HasColumnType("integer")
                        .HasColumnName("idPanier");

                    b.Property<int?>("IdSejour")
                        .HasColumnType("integer")
                        .HasColumnName("idSejour");

                    b.Property<int?>("NbAdultes")
                        .HasColumnType("integer")
                        .HasColumnName("nbAdultes");

                    b.Property<int?>("NbChambresDouble")
                        .HasColumnType("integer")
                        .HasColumnName("nbChambresDouble");

                    b.Property<int?>("NbChambresSimple")
                        .HasColumnType("integer")
                        .HasColumnName("nbChambresSimple");

                    b.Property<int?>("NbChambresTriple")
                        .HasColumnType("integer")
                        .HasColumnName("nbChambresTriple");

                    b.Property<int?>("NbEnfants")
                        .HasColumnType("integer")
                        .HasColumnName("nbEnfants");

                    b.Property<bool?>("Offrir")
                        .HasColumnType("boolean")
                        .HasColumnName("offrir");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("IdDescriptionPanier")
                        .HasName("pk_descriptionpanier");

                    b.HasIndex("IdHebergement");

                    b.HasIndex("IdPanier");

                    b.HasIndex("IdSejour");

                    b.ToTable("DESCRIPTIONPANIER");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Duree", b =>
                {
                    b.Property<int>("IdDuree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idDuree");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDuree"));

                    b.Property<string>("LibelleDuree")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleDuree");

                    b.HasKey("IdDuree")
                        .HasName("pk_duree");

                    b.ToTable("DUREE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.EstProposePar", b =>
                {
                    b.Property<int>("Idpartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idpartenaire");

                    b.Property<int>("Idactivite")
                        .HasColumnType("integer")
                        .HasColumnName("idactivite");

                    b.Property<int>("Idadresse")
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    b.HasKey("Idpartenaire", "Idactivite", "Idadresse")
                        .HasName("pk_est_propose_par");

                    b.HasIndex("Idactivite");

                    b.HasIndex("Idadresse");

                    b.ToTable("EstProposePars");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Etape", b =>
                {
                    b.Property<int>("IdEtape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idEtape");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEtape"));

                    b.Property<string>("DescriptionEtape")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("descriptionEtape");

                    b.Property<int?>("IdHebergement")
                        .HasColumnType("integer")
                        .HasColumnName("idHebergement");

                    b.Property<int?>("IdSejour")
                        .HasColumnType("integer")
                        .HasColumnName("idSejour");

                    b.Property<string>("PhotoEtape")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoEtape");

                    b.Property<string>("TitreEtape")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titreEtape");

                    b.Property<string>("URLEtape")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("URLEtape");

                    b.Property<string>("VideoEtape")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("videoEtape");

                    b.HasKey("IdEtape")
                        .HasName("pk_etape");

                    b.HasIndex("IdHebergement");

                    b.HasIndex("IdSejour");

                    b.ToTable("ETAPE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Hebergement", b =>
                {
                    b.Property<int>("IdHebergement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idHebergement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHebergement"));

                    b.Property<string>("DescriptionHebergement")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("descriptionHebergement");

                    b.Property<int>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<string>("LienHebergement")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("lienHebergement");

                    b.Property<string>("PhotoHebergement")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoHebergement");

                    b.Property<decimal?>("PrixHebergement")
                        .HasColumnType("NUMERIC(8,2)")
                        .HasColumnName("prixHebergement");

                    b.HasKey("IdHebergement")
                        .HasName("pk_hebergement");

                    b.HasIndex("IdPartenaire");

                    b.ToTable("HEBERGEMENT");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Hotel", b =>
                {
                    b.Property<int>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<int?>("CategorieHotel")
                        .HasColumnType("integer")
                        .HasColumnName("categorieHotel");

                    b.Property<string>("MailPartenaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mailPartenaire");

                    b.Property<string>("NomPartenaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomPartenaire");

                    b.Property<int?>("NombreChambresHotel")
                        .HasColumnType("integer")
                        .HasColumnName("nombreChambresHotel");

                    b.Property<string>("TelPartenaire")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telPartenaire")
                        .IsFixedLength();

                    b.HasKey("IdPartenaire")
                        .HasName("pk_hotel");

                    b.ToTable("HOTEL");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Localite", b =>
                {
                    b.Property<int>("IdLocalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idLocalite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocalite"));

                    b.Property<int?>("IdCategorieVignoble")
                        .HasColumnType("integer")
                        .HasColumnName("idCategorieVignoble");

                    b.Property<string>("LibelleLocalite")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleLocalite");

                    b.HasKey("IdLocalite")
                        .HasName("pk_localite");

                    b.HasIndex("IdCategorieVignoble");

                    b.ToTable("LOCALITE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idPanier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPanier"));

                    b.Property<DateTime?>("DateAjoutPanier")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateAjoutPanier");

                    b.Property<int?>("IdCodePromo")
                        .HasColumnType("integer")
                        .HasColumnName("idCodePromo");

                    b.HasKey("IdPanier")
                        .HasName("pk_panier");

                    b.HasIndex("IdCodePromo");

                    b.ToTable("PANIER");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Partenaire", b =>
                {
                    b.Property<int>("IdPartenaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartenaire"));

                    b.Property<string>("MailPartenaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mailPartenaire");

                    b.Property<string>("NomPartenaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomPartenaire");

                    b.Property<string>("TelPartenaire")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telPartenaire")
                        .IsFixedLength();

                    b.HasKey("IdPartenaire")
                        .HasName("pk_partenaire");

                    b.ToTable("PARTENAIRE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("IdPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idPhoto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhoto"));

                    b.Property<int>("IdSejour")
                        .HasColumnType("integer")
                        .HasColumnName("idSejour");

                    b.HasKey("IdPhoto")
                        .HasName("pk_photos");

                    b.HasIndex("IdSejour");

                    b.ToTable("PHOTO");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Repas", b =>
                {
                    b.Property<int>("IdRepas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRepas");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRepas"));

                    b.Property<string>("DescriptionRepas")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("descriptionRepas");

                    b.Property<int?>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<string>("PhotoRepas")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoRepas");

                    b.Property<decimal?>("PrixRepas")
                        .HasColumnType("NUMERIC(8,2)")
                        .HasColumnName("prixRepas");

                    b.HasKey("IdRepas")
                        .HasName("pk_repas");

                    b.HasIndex("IdPartenaire");

                    b.ToTable("REPAS");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Reponse", b =>
                {
                    b.Property<int>("IdReponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idReponse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReponse"));

                    b.Property<string>("DescriptionReponse")
                        .HasMaxLength(2056)
                        .HasColumnType("character varying(2056)")
                        .HasColumnName("descriptionReponse");

                    b.Property<int?>("IdAvis")
                        .HasColumnType("integer")
                        .HasColumnName("idAvis");

                    b.HasKey("IdReponse")
                        .HasName("pk_reponse");

                    b.HasIndex("IdAvis");

                    b.ToTable("REPONSE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Restaurant", b =>
                {
                    b.Property<int>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<int?>("IdTypeCuisine")
                        .HasColumnType("integer")
                        .HasColumnName("idTypeCuisine");

                    b.Property<string>("MailPartenaire")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mailPartenaire");

                    b.Property<string>("NomPartenaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomPartenaire");

                    b.Property<int?>("NombreEtoilesRestaurant")
                        .HasColumnType("integer")
                        .HasColumnName("nombreEtoilesRestaurant");

                    b.Property<string>("SpecialiteRestaurant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("specialiteRestaurant");

                    b.Property<string>("TelPartenaire")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telPartenaire")
                        .IsFixedLength();

                    b.HasKey("IdPartenaire")
                        .HasName("pk_restaurant");

                    b.HasIndex("IdTypeCuisine");

                    b.ToTable("RESTAURANT");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRole");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<string>("LibelleRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleRole");

                    b.HasKey("IdRole")
                        .HasName("pk_roles");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.RouteDesVins", b =>
                {
                    b.Property<int>("IdRoute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idRoute");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRoute"));

                    b.Property<string>("DescriptionRoute")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("descriptionRoute");

                    b.Property<string>("LibRoute")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libRoute");

                    b.Property<string>("PhotoRoute")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoRoute");

                    b.HasKey("IdRoute")
                        .HasName("pk_route_des_vins");

                    b.ToTable("ROUTE_DES_VINS");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Sejour", b =>
                {
                    b.Property<int>("Idsejour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idsejour");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idsejour"));

                    b.Property<string>("Descriptionsejour")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("descriptionsejour");

                    b.Property<int>("Idcategorieparticipant")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorieparticipant");

                    b.Property<int>("Idcategoriesejour")
                        .HasColumnType("integer")
                        .HasColumnName("idcategoriesejour");

                    b.Property<int>("Idcategorievignoble")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorievignoble");

                    b.Property<int>("Idduree")
                        .HasColumnType("integer")
                        .HasColumnName("idduree");

                    b.Property<int?>("Idlocalite")
                        .HasColumnType("integer")
                        .HasColumnName("idlocalite");

                    b.Property<int>("Idtheme")
                        .HasColumnType("integer")
                        .HasColumnName("idtheme");

                    b.Property<decimal?>("Nouveauprixsejour")
                        .HasColumnType("NUMERIC(8,2)")
                        .HasColumnName("nouveauprixsejour");

                    b.Property<string>("Photosejour")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photosejour");

                    b.Property<decimal?>("Prixsejour")
                        .HasColumnType("NUMERIC(8,2)")
                        .HasColumnName("prixsejour");

                    b.Property<bool?>("Publie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("publie");

                    b.Property<string>("Titresejour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titresejour");

                    b.HasKey("Idsejour")
                        .HasName("pk_sejour");

                    b.HasIndex("Idcategorieparticipant");

                    b.HasIndex("Idcategoriesejour");

                    b.HasIndex("Idcategorievignoble");

                    b.HasIndex("Idduree");

                    b.HasIndex("Idlocalite");

                    b.HasIndex("Idtheme");

                    b.ToTable("sejour");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Theme", b =>
                {
                    b.Property<int>("IdTheme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTheme");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTheme"));

                    b.Property<string>("LibelleTheme")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleTheme");

                    b.HasKey("IdTheme")
                        .HasName("pk_theme");

                    b.ToTable("THEME");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.TypeCuisine", b =>
                {
                    b.Property<int>("IdTypeCuisine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTypeCuisine");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeCuisine"));

                    b.Property<string>("LibelleTypeCuisine")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleTypeCuisine");

                    b.HasKey("IdTypeCuisine")
                        .HasName("pk_typecuisine");

                    b.ToTable("TYPECUISINE");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.TypeDegustation", b =>
                {
                    b.Property<int>("IdTypeDegustation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTypeDegustation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeDegustation"));

                    b.Property<string>("LibelleTypeDegustation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libelleTypeDegustation");

                    b.HasKey("IdTypeDegustation")
                        .HasName("pk_typedegustation");

                    b.ToTable("TYPEDEGUSTATION");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Visite", b =>
                {
                    b.Property<int>("IdVisite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idVisite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVisite"));

                    b.Property<string>("DescriptionVisite")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("descriptionVisite");

                    b.Property<int?>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idPartenaire");

                    b.Property<string>("LienVisite")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("lienVisite");

                    b.Property<string>("PhotoVisite")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photoVisite");

                    b.HasKey("IdVisite")
                        .HasName("pk_visite");

                    b.HasIndex("IdPartenaire");

                    b.ToTable("VISITE");
                });

            modelBuilder.Entity("Appartient", b =>
                {
                    b.Property<int>("Idvisite")
                        .HasColumnType("integer");

                    b.Property<int>("Idetape")
                        .HasColumnType("integer");

                    b.Property<int>("IdEtape")
                        .HasColumnType("integer");

                    b.Property<int>("IdVisite")
                        .HasColumnType("integer");

                    b.HasKey("Idvisite", "Idetape")
                        .HasName("pk_appartient");

                    b.HasIndex("Idetape");

                    b.ToTable("appartient", (string)null);
                });

            modelBuilder.Entity("Comporte", b =>
                {
                    b.Property<int>("Idactivite")
                        .HasColumnType("integer");

                    b.Property<int>("Iddescriptionpanier")
                        .HasColumnType("integer");

                    b.Property<int>("IdActivite")
                        .HasColumnType("integer");

                    b.Property<int>("IdDescriptionPanier")
                        .HasColumnType("integer");

                    b.HasKey("Idactivite", "Iddescriptionpanier")
                        .HasName("pk_comporte");

                    b.HasIndex("Iddescriptionpanier");

                    b.ToTable("comporte", (string)null);
                });

            modelBuilder.Entity("Constitue", b =>
                {
                    b.Property<int>("Idactivite")
                        .HasColumnType("integer");

                    b.Property<int>("Idetape")
                        .HasColumnType("integer");

                    b.Property<int>("IdActivite")
                        .HasColumnType("integer");

                    b.Property<int>("IdEtape")
                        .HasColumnType("integer");

                    b.HasKey("Idactivite", "Idetape")
                        .HasName("pk_constitue");

                    b.HasIndex("Idetape");

                    b.ToTable("constitue", (string)null);
                });

            modelBuilder.Entity("Detient", b =>
                {
                    b.Property<int>("Idrepas")
                        .HasColumnType("integer");

                    b.Property<int>("Iddescriptionpanier")
                        .HasColumnType("integer");

                    b.Property<int>("IdDescriptionPanier")
                        .HasColumnType("integer");

                    b.Property<int>("IdRepas")
                        .HasColumnType("integer");

                    b.HasKey("Idrepas", "Iddescriptionpanier")
                        .HasName("pk_detient");

                    b.HasIndex("Iddescriptionpanier");

                    b.ToTable("detient", (string)null);
                });

            modelBuilder.Entity("Favori", b =>
                {
                    b.Property<int>("Idclient")
                        .HasColumnType("integer");

                    b.Property<int>("Idsejour")
                        .HasColumnType("integer");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.HasKey("Idclient", "Idsejour")
                        .HasName("pk_favoris");

                    b.HasIndex("Idsejour");

                    b.ToTable("favoris", (string)null);
                });

            modelBuilder.Entity("Inclu", b =>
                {
                    b.Property<int>("Idrepas")
                        .HasColumnType("integer");

                    b.Property<int>("Idetape")
                        .HasColumnType("integer");

                    b.Property<int>("IdEtape")
                        .HasColumnType("integer");

                    b.Property<int>("IdRepas")
                        .HasColumnType("integer");

                    b.HasKey("Idrepas", "Idetape")
                        .HasName("pk_inclus");

                    b.HasIndex("Idetape");

                    b.ToTable("inclus", (string)null);
                });

            modelBuilder.Entity("Mange1", b =>
                {
                    b.Property<int>("Idrepas")
                        .HasColumnType("integer");

                    b.Property<int>("Iddescriptioncommande")
                        .HasColumnType("integer");

                    b.Property<int>("IdRepas")
                        .HasColumnType("integer");

                    b.HasKey("Idrepas", "Iddescriptioncommande")
                        .HasName("pk_contient");

                    b.HasIndex("Iddescriptioncommande");

                    b.ToTable("mange1", (string)null);
                });

            modelBuilder.Entity("Possede", b =>
                {
                    b.Property<int>("Idactivite")
                        .HasColumnType("integer");

                    b.Property<int>("Iddescriptioncommande")
                        .HasColumnType("integer");

                    b.Property<int>("IdDescriptionCommande")
                        .HasColumnType("integer");

                    b.HasKey("Idactivite", "Iddescriptioncommande")
                        .HasName("pk_possede");

                    b.HasIndex("Iddescriptioncommande");

                    b.ToTable("possede", (string)null);
                });

            modelBuilder.Entity("SeLocalise", b =>
                {
                    b.Property<int>("Idroute")
                        .HasColumnType("integer");

                    b.Property<int>("Idcategorievignoble")
                        .HasColumnType("integer");

                    b.Property<int>("IdCategorieVignoble")
                        .HasColumnType("integer");

                    b.Property<int>("IdRoute")
                        .HasColumnType("integer");

                    b.HasKey("Idroute", "Idcategorievignoble")
                        .HasName("pk_se_localise");

                    b.HasIndex("Idcategorievignoble");

                    b.ToTable("se_localise", (string)null);
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Adresse", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Client", "Client")
                        .WithMany("Adresses")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_adresse_associati_client");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Partenaire", "Partenaire")
                        .WithMany("AdressesPartenaires")
                        .HasForeignKey("IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_adresse_localise_partenai");

                    b.Navigation("Client");

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.AutreSociete", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Partenaire", "Partenaire")
                        .WithOne("AutreSocietePartenaire")
                        .HasForeignKey("APIVinotrip.Models.EntityFramework.AutreSociete", "IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_autresoc_heritage__partenai");

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Avis", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Client", "Client")
                        .WithMany("LesAvis")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_avis_associati_client");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Sejour", "Sejour")
                        .WithMany("AvisNavigation")
                        .HasForeignKey("IdSejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_avis_critique_sejour");

                    b.Navigation("Client");

                    b.Navigation("Sejour");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Client", "Client")
                        .WithMany("CartesBancaires")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_carte_ba_associati_client");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Cave", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Partenaire", "Partenaire")
                        .WithOne("Caves")
                        .HasForeignKey("APIVinotrip.Models.EntityFramework.Cave", "IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cave_heritage__partenai");

                    b.HasOne("APIVinotrip.Models.EntityFramework.TypeDegustation", "TypeDegustation")
                        .WithMany("Caves")
                        .HasForeignKey("IdTypeDegustation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cave_fait_degu_typedegu");

                    b.Navigation("Partenaire");

                    b.Navigation("TypeDegustation");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Client", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Role", "Role")
                        .WithMany("Clients")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_client_associati_roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Adresse", "AdresseFacturation")
                        .WithMany("CommandesFacturation")
                        .HasForeignKey("IdAdresseFacturation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commande_associati_adresse2");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Adresse", "AdresseLivraison")
                        .WithMany("CommandesLivraison")
                        .HasForeignKey("IdAdresseLivraison")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commande_associati_adresse");

                    b.HasOne("APIVinotrip.Models.EntityFramework.CarteBancaire", "CarteBancaire")
                        .WithMany("Commandes")
                        .HasForeignKey("IdCB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commande_associati_carte_ba");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Client", "ClientAcheteur")
                        .WithMany("Commandes")
                        .HasForeignKey("IdClientAcheteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commande_associati_client2");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Client", "ClientBeneficiaire")
                        .WithMany("CommandesOfferts")
                        .HasForeignKey("IdClientBeneficiaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commande_associati_client");

                    b.HasOne("APIVinotrip.Models.EntityFramework.CodePromo", "CodeReductionNavigation")
                        .WithMany("Commandes")
                        .HasForeignKey("IdCodePromo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commande_diminue_codeprom");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Panier", "PanierCommande")
                        .WithMany("Commandes")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commande_associe_panier");

                    b.Navigation("AdresseFacturation");

                    b.Navigation("AdresseLivraison");

                    b.Navigation("CarteBancaire");

                    b.Navigation("ClientAcheteur");

                    b.Navigation("ClientBeneficiaire");

                    b.Navigation("CodeReductionNavigation");

                    b.Navigation("PanierCommande");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.DescriptionCommande", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.CarteBancaire", "DescriptionsCommandeCB")
                        .WithMany("DescriptionsCommande")
                        .HasForeignKey("IdCB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_associati_carte_ba");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Commande", "Commande")
                        .WithMany("DescriptionsCommande")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_associati_commande");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Hebergement", "Hebergements")
                        .WithMany("DescriptionsCommande")
                        .HasForeignKey("IdHebergement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_associati_hebergem");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Sejour", "Sejours")
                        .WithMany("DescriptioncommandesNavigation")
                        .HasForeignKey("IdSejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_associati_sejour");

                    b.Navigation("Commande");

                    b.Navigation("DescriptionsCommandeCB");

                    b.Navigation("Hebergements");

                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.DescriptionPanier", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Hebergement", "Hebergement")
                        .WithMany("DescriptionsPanier")
                        .HasForeignKey("IdHebergement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_associati_hebergem");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Panier", "Panier")
                        .WithMany("DescriptionsPanier")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_decrit_pa_panier");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Sejour", "Sejour")
                        .WithMany("Descriptionpaniers")
                        .HasForeignKey("IdSejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_descript_decrit_se_sejour");

                    b.Navigation("Hebergement");

                    b.Navigation("Panier");

                    b.Navigation("Sejour");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.EstProposePar", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Activite", "IdactiviteNavigation")
                        .WithMany("EstProposePars")
                        .HasForeignKey("Idactivite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propose__propose_5_activite");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Adresse", "IdadresseNavigation")
                        .WithMany("EstProposePars")
                        .HasForeignKey("Idadresse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propose__propose_6_adresse");

                    b.HasOne("APIVinotrip.Models.EntityFramework.AutreSociete", "IdpartenaireNavigation")
                        .WithMany("EstProposePars")
                        .HasForeignKey("Idpartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propose__est_propose_par_autresoc");

                    b.Navigation("IdactiviteNavigation");

                    b.Navigation("IdadresseNavigation");

                    b.Navigation("IdpartenaireNavigation");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Etape", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Hebergement", "Hebergement")
                        .WithMany("Etapes")
                        .HasForeignKey("IdHebergement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_etape_appartien_hebergem");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Sejour", "Sejour")
                        .WithMany("Etapes")
                        .HasForeignKey("IdSejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_etape_possede_sejour");

                    b.Navigation("Hebergement");

                    b.Navigation("Sejour");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Hebergement", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Hotel", "HebergementHotel")
                        .WithMany("HotelHebergements")
                        .HasForeignKey("IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hebergem_propose_3_hotel");

                    b.Navigation("HebergementHotel");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Hotel", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Partenaire", "Partenaire")
                        .WithOne("HotelPartenaire")
                        .HasForeignKey("APIVinotrip.Models.EntityFramework.Hotel", "IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_heritage__partenai");

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Localite", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.CategorieVignoble", "CategoriesVignoble")
                        .WithMany("Localites")
                        .HasForeignKey("IdCategorieVignoble")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_localite_a_categori");

                    b.Navigation("CategoriesVignoble");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Panier", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.CodePromo", "CodesPromos")
                        .WithMany("Paniers")
                        .HasForeignKey("IdCodePromo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_panier_reduit_codeprom");

                    b.Navigation("CodesPromos");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Photo", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Sejour", "Sejour")
                        .WithMany("Photos")
                        .HasForeignKey("IdSejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_photos_associati_sejour");

                    b.Navigation("Sejour");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Repas", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Restaurant", "RestaurantRepas")
                        .WithMany("RepasCollection")
                        .HasForeignKey("IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_repas_propose_2_restaura");

                    b.Navigation("RestaurantRepas");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Reponse", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Avis", "Avis")
                        .WithMany("Reponses")
                        .HasForeignKey("IdAvis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reponse_repond_avis");

                    b.Navigation("Avis");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Restaurant", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Partenaire", "Partenaire")
                        .WithOne("Restaurants")
                        .HasForeignKey("APIVinotrip.Models.EntityFramework.Restaurant", "IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_restaura_heritage__partenai");

                    b.HasOne("APIVinotrip.Models.EntityFramework.TypeCuisine", "TypeCuisine")
                        .WithMany("Restaurants")
                        .HasForeignKey("IdTypeCuisine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_restaura_cuisine_typecuis");

                    b.Navigation("Partenaire");

                    b.Navigation("TypeCuisine");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Sejour", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.CategorieParticipant", "IdcategorieparticipantNavigation")
                        .WithMany("Sejours")
                        .HasForeignKey("Idcategorieparticipant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sejour_destine_a_categori");

                    b.HasOne("APIVinotrip.Models.EntityFramework.CategorieSejour", "IdcategoriesejourNavigation")
                        .WithMany("Sejours")
                        .HasForeignKey("Idcategoriesejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sejour_regroupe_categori");

                    b.HasOne("APIVinotrip.Models.EntityFramework.CategorieVignoble", "IdcategorievignobleNavigation")
                        .WithMany("Sejours")
                        .HasForeignKey("Idcategorievignoble")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sejour_categoris_categori");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Duree", "IddureeNavigation")
                        .WithMany("Sejours")
                        .HasForeignKey("Idduree")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sejour_dure_duree");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Localite", "IdlocaliteNavigation")
                        .WithMany("Sejours")
                        .HasForeignKey("Idlocalite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sejour_se_situe_localite");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Theme", "IdthemeNavigation")
                        .WithMany("Sejours")
                        .HasForeignKey("Idtheme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sejour_definit_theme");

                    b.Navigation("IdcategorieparticipantNavigation");

                    b.Navigation("IdcategoriesejourNavigation");

                    b.Navigation("IdcategorievignobleNavigation");

                    b.Navigation("IddureeNavigation");

                    b.Navigation("IdlocaliteNavigation");

                    b.Navigation("IdthemeNavigation");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Visite", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Cave", "Cave")
                        .WithMany("Visites")
                        .HasForeignKey("IdPartenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_visite_propose_1_cave");

                    b.Navigation("Cave");
                });

            modelBuilder.Entity("Appartient", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Etape", null)
                        .WithMany()
                        .HasForeignKey("Idetape")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appartie_appartien_etape");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Visite", null)
                        .WithMany()
                        .HasForeignKey("Idvisite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appartie_appartien_visite");
                });

            modelBuilder.Entity("Comporte", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Activite", null)
                        .WithMany()
                        .HasForeignKey("Idactivite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_activite");

                    b.HasOne("APIVinotrip.Models.EntityFramework.DescriptionPanier", null)
                        .WithMany()
                        .HasForeignKey("Iddescriptionpanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_descript");
                });

            modelBuilder.Entity("Constitue", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Activite", null)
                        .WithMany()
                        .HasForeignKey("Idactivite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appartie_appartien_activite");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Etape", null)
                        .WithMany()
                        .HasForeignKey("Idetape")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appartie_appartien_etape");
                });

            modelBuilder.Entity("Detient", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.DescriptionPanier", null)
                        .WithMany()
                        .HasForeignKey("Iddescriptionpanier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_descript");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Repas", null)
                        .WithMany()
                        .HasForeignKey("Idrepas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_repas");
                });

            modelBuilder.Entity("Favori", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Client", null)
                        .WithMany()
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favoris_favoris_client");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Sejour", null)
                        .WithMany()
                        .HasForeignKey("Idsejour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favoris_favoris2_sejour");
                });

            modelBuilder.Entity("Inclu", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Etape", null)
                        .WithMany()
                        .HasForeignKey("Idetape")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appartie_appartien_etape");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Repas", null)
                        .WithMany()
                        .HasForeignKey("Idrepas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appartie_appartien_repas");
                });

            modelBuilder.Entity("Mange1", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.DescriptionCommande", null)
                        .WithMany()
                        .HasForeignKey("Iddescriptioncommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_descript");

                    b.HasOne("APIVinotrip.Models.EntityFramework.Repas", null)
                        .WithMany()
                        .HasForeignKey("Idrepas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_repas");
                });

            modelBuilder.Entity("Possede", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.Activite", null)
                        .WithMany()
                        .HasForeignKey("Idactivite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_activite");

                    b.HasOne("APIVinotrip.Models.EntityFramework.DescriptionCommande", null)
                        .WithMany()
                        .HasForeignKey("Iddescriptioncommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_associat_associati_descript");
                });

            modelBuilder.Entity("SeLocalise", b =>
                {
                    b.HasOne("APIVinotrip.Models.EntityFramework.CategorieVignoble", null)
                        .WithMany()
                        .HasForeignKey("Idcategorievignoble")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_se_local_se_locali_categori");

                    b.HasOne("APIVinotrip.Models.EntityFramework.RouteDesVins", null)
                        .WithMany()
                        .HasForeignKey("Idroute")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_se_local_se_locali_route_de");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Activite", b =>
                {
                    b.Navigation("EstProposePars");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("CommandesFacturation");

                    b.Navigation("CommandesLivraison");

                    b.Navigation("EstProposePars");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.AutreSociete", b =>
                {
                    b.Navigation("EstProposePars");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Avis", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("DescriptionsCommande");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CategorieParticipant", b =>
                {
                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CategorieSejour", b =>
                {
                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CategorieVignoble", b =>
                {
                    b.Navigation("Localites");

                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Cave", b =>
                {
                    b.Navigation("Visites");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Client", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("CartesBancaires");

                    b.Navigation("Commandes");

                    b.Navigation("CommandesOfferts");

                    b.Navigation("LesAvis");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.CodePromo", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Paniers");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Commande", b =>
                {
                    b.Navigation("DescriptionsCommande");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Duree", b =>
                {
                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Hebergement", b =>
                {
                    b.Navigation("DescriptionsCommande");

                    b.Navigation("DescriptionsPanier");

                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Hotel", b =>
                {
                    b.Navigation("HotelHebergements");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Localite", b =>
                {
                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Panier", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("DescriptionsPanier");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Partenaire", b =>
                {
                    b.Navigation("AdressesPartenaires");

                    b.Navigation("AutreSocietePartenaire");

                    b.Navigation("Caves");

                    b.Navigation("HotelPartenaire");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Restaurant", b =>
                {
                    b.Navigation("RepasCollection");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Role", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Sejour", b =>
                {
                    b.Navigation("AvisNavigation");

                    b.Navigation("DescriptioncommandesNavigation");

                    b.Navigation("Descriptionpaniers");

                    b.Navigation("Etapes");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.Theme", b =>
                {
                    b.Navigation("Sejours");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.TypeCuisine", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("APIVinotrip.Models.EntityFramework.TypeDegustation", b =>
                {
                    b.Navigation("Caves");
                });
#pragma warning restore 612, 618
        }
    }
}
